document.getElementById('quoteButton').addEventListener('click', function() {
    const quotes = [
        "The best way to predict the future is to invent it. – Alan Kay",
        "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
        "It does not matter how slowly you go as long as you do not stop. – Confucius",
        "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. – Thomas A. Edison",
        "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
        "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
        "Believe you can and you're halfway there. – Theodore Roosevelt",
        "To succeed in life, you need two things: ignorance and confidence. – Mark Twain",
        "Act as if what you do makes a difference. It does. – William James",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
        "Never bend your head. Always hold it high. Look the world straight in the eye. – Helen Keller",
        "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
        "Believe you can and you're halfway there. – Theodore Roosevelt",
        "When you have a dream, you've got to grab it and never let go. – Carol Burnett",
        "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. – Jimmy Dean",
        "No matter what you're going through, there's a light at the end of the tunnel. – Demi Lovato",
        "It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome. – William James",
        "Life is like riding a bicycle. To keep your balance, you must keep moving. – Albert Einstein",
        "Just don't give up trying to do what you really want to do. Where there is love and inspiration, I don't think you can go wrong. – Ella Fitzgerald",
        "Limit your 'always' and your 'nevers.' – Amy Poehler",
        "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
        "Try to be a rainbow in someone's cloud. – Maya Angelou",
        "You do not find the happy life. You make it. – Camilla Eyring Kimball",
        "The most wasted of days is one without laughter. – E.E. Cummings",
        "You must do the things you think you cannot do. – Eleanor Roosevelt",
        "Be the change that you wish to see in the world. – Mahatma Gandhi",
        "Let us make our future now, and let us make our dreams tomorrow's reality. – Malala Yousafzai",
        "You get what you give. – Jennifer Lopez",
        "Today is your opportunity to build the tomorrow you want. – Ken Poirot",
        "Innovation distinguishes between a leader and a follower. – Steve Jobs",
        "Learning never exhausts the mind. – Leonardo da Vinci",
        "The only way to do great work is to love what you do. – Steve Jobs",
        "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
        "Do what you can with all you have, wherever you are. – Theodore Roosevelt",
        "What we think, we become. – Buddha",
        "All limitations are self-imposed. – Oliver Wendell Holmes",
        "Tough times never last but tough people do. – Robert H. Schuller",
        "Problems are not stop signs, they are guidelines. – Robert H. Schuller",
        "One day or day one. You decide. – Unknown",
        "Whoever is happy will make others happy too. – Anne Frank",
        "Do what is right, not what is easy nor what is popular. – Roy T. Bennett",
        "I failed my way to success. – Thomas Edison",
        "He who has a why to live can bear almost any how. – Friedrich Nietzsche",
        "Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers. – Socrates",
        "Do something today that your future self will thank you for. – Sean Patrick Flanery",
        "Happiness is not something ready made. It comes from your own actions. – Dalai Lama XIV",
        "Whatever you are, be a good one. – Abraham Lincoln",
        "The power of imagination makes us infinite. – John Muir",
        "May your choices reflect your hopes, not your fears. – Nelson Mandela",
        "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
        "Every moment is a fresh beginning. – T.S. Eliot",
        "Everything you can imagine is real. – Pablo Picasso",
        "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
        "Change the world by being yourself. – Amy Poehler",
        "Gratitude is a powerful catalyst for happiness. – Amy Collette",
        "What you seek is seeking you. – Rumi",
        "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
        "Begin anywhere. – John Cage"
]

    ];
    const quote = quotes[Math.floor(Math.random() * quotes.length)];
    document.getElementById('quote').textContent = quote;
});
